import assert from 'node:assert/strict';
import { createRenderer, h } from 'vue';
let receiver;
const sent=[];
globalThis.window={external:{receiveMessage:handler=>{receiver=handler;},sendMessage:message=>sent.push(JSON.parse(message))}};
const { useWindowRole }=await import('../src/composables/useWindowRole.js');
const renderer=createRenderer({createElement:()=>({}),insert(){},remove(){},setElementText(){},patchProp(){},createText:()=>({}),createComment:()=>({}),setText(){},parentNode(){},nextSibling(){}});
let role;
const app=renderer.createApp({setup(){role=useWindowRole();return()=>h('div');}});
app.mount({});
assert.deepEqual(sent,[{type:'getWindowRole'}]);
assert.equal(role.isHelperWindow.value,false);
receiver(JSON.stringify({type:'windowRole',role:'helper'}));
assert.equal(role.isHelperWindow.value,true);
receiver(JSON.stringify({type:'zoomState',percent:100}));
assert.equal(role.isHelperWindow.value,true);
receiver(JSON.stringify({type:'windowRole',role:'main'}));
assert.equal(role.isHelperWindow.value,false);
app.unmount();
receiver(JSON.stringify({type:'windowRole',role:'helper'}));
assert.equal(role.isHelperWindow.value,false);
delete globalThis.window;
console.log('Helper appearance follows native window identity and cleans up subscriptions');
